services:
  mysql:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: orderstracker
      MYSQL_USER: appuser
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork
      
  backend:
    build: ./backend/ordertracker
    container_name: spring_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/orderstracker
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: app_password
    depends_on:
      - mysql
    networks:
      - mynetwork
      
  react-nginx:
    build:
      context: .
      dockerfile: Dockerfile.react-nginx
    container_name: react-nginx
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - mynetwork
      
networks:
  mynetwork:
    
volumes:
  mysql_data:

